import Head from "next/head";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Google Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body className="relative min-h-screen">
        {children}

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
